#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : parsedatetime
Version  : 2.2
Release  : 3
URL      : https://pypi.python.org/packages/62/a3/0c546deec0c1ea5e20320daf7719df9419c2bee97f1a11b9feaf0143b0fc/parsedatetime-2.2.tar.gz
Source0  : https://pypi.python.org/packages/62/a3/0c546deec0c1ea5e20320daf7719df9419c2bee97f1a11b9feaf0143b0fc/parsedatetime-2.2.tar.gz
Summary  : Parse human-readable date/time text.
Group    : Development/Tools
License  : Apache-2.0
Requires: parsedatetime-python
BuildRequires : pbr
BuildRequires : pip
BuildRequires : pytest-runner
BuildRequires : python-dev
BuildRequires : python-future
BuildRequires : python3-dev
BuildRequires : setuptools

%description
parsedatetime
Parse human-readable date/time strings.
Python 2.6 or greater is required for parsedatetime version 1.0 or greater.

%package python
Summary: python components for the parsedatetime package.
Group: Default

%description python
python components for the parsedatetime package.


%prep
%setup -q -n parsedatetime-2.2

%build
export LANG=C
export SOURCE_DATE_EPOCH=1486056346
python2 setup.py build -b py2
python3 setup.py build -b py3

%check
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
PYTHONPATH=%{buildroot}/usr/lib/python2.7/site-packages python2 setup.py test
%install
export SOURCE_DATE_EPOCH=1486056346
rm -rf %{buildroot}
python2 -tt setup.py build -b py2 install --root=%{buildroot} --force
python3 -tt setup.py build -b py3 install --root=%{buildroot} --force

%files
%defattr(-,root,root,-)

%files python
%defattr(-,root,root,-)
/usr/lib/python*/*
